### ISSUE TITLE
[Request] Support rule for unused imports

### ISSUE THREAD

**Issue by nodegin** [gajus/eslint-plugin-canonical#14]
Hi, thank you for this awesome plugin!

It would be really nice to integrate [eslint-plugin-unused-imports](https://github.com/sweepline/eslint-plugin-unused-imports),

which also lint unused vars for imports.

Thanks.

**Comment by gajus** [comment]
I cannot understand what is the purpose of that plugin if `no-unsed-vars` does the same thing?

**Comment by nodegin** [comment]
@gajus Sorry my fault, it seems my rule being overriden by the preset extended
