### ISSUE TITLE
`no-unused-exports` bug with `export * from` syntax

### ISSUE THREAD

**Issue by omothm** [gajus/eslint-plugin-canonical#24]
When a file uses the syntax

```ts
export * from "./file.ts";
```

where `file.ts` contains more than one export on separate lines, the rule throws a RangeError.

**Minimal reproduction:** https://github.com/omothm/no-unused-exports-export-from-bug-repro

**Comment by AnasShahid** [comment]
A simple workaround I did was to exclude the barrel file from eslint using tsconfig.eslint.json file.  Here's the sample **tsconfig.eslint.json** file:

`{
  "extends": "./tsconfig.json",
  "include": [
    "src/**/*.ts",
    "*.ts",
    "test/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "dist",
    ".eslintrc.js",
    "src/**/index.ts" // Removing barrel file from eslint because 'export *' syntax conflicts with the cononical/no-unused-exports rule.
  ]
}
`

**Comment by gajus** [comment]
I encourage to migrate to https://knip.dev/
