### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by zloirock** [gajus/eslint-plugin-canonical#30]
After moving `eslint-plugin-filenames` -> `eslint-plugin-canonical`, I found that the volume of linting dependencies has almost doubled from what it was - but it was dependencies of `eslint` with 14 heavy plugins.

https://github.com/zloirock/core-js/commit/3e58c09501e2a12cba6d246ef9d12c87f07a590a, see `tests/eslint/package-lock.json`.

Is it possible somehow reduce it?

**Comment by gajus** [comment]
Not something that I am planning to tackle.
