### ISSUE TITLE
[Feature request] virtual-module feature should allow for nested virtual modules

### ISSUE THREAD

**Issue by gabriel-calin-lazar** [gajus/eslint-plugin-canonical#31]
Bug report or Feature request?

Feature request

Information

virtual-module feature should allow for nested virtual modules
a parent virtual modules should be able to re-export members from nested - child - virtual modules

components/
├── Foo/
 │   └── index.ts
 │   └── Qux/
 │       └── index.ts/
 │           └── Quux/
 │               └── index.ts
└── Bar

Qux should be able to re-export from Quux
Foo should be able to re-export from Qux
Bar should be able to import from Foo

if specific members of Quux are re-exported by Qux
and
same specific members are re-exported by Foo
then 
Bar should be able to import them from Foo

currently, this is not supported as we get
 Cannot import a private path. /index.ts belongs to parent virtual module
when re-exporting from nested virtual module

**Comment by gajus** [comment]
VM was removed entirely.
