### ISSUE TITLE
ESlint 9 and flat config compatibility

### ISSUE THREAD

**Issue by rzschoch** [gajus/eslint-plugin-canonical#37]
I would like to use the plugin with ESlint 9. To achieve this, the configuration must be written in flat config format. My attempts to get the plugin to work have unfortunately failed.

Is it officially compatible with ESlint 9 and the flat config? Would it be possible to provide an example of the configuration in this format?

**Comment by gajus** [comment]
It is being used in https://github.com/gajus/eslint-config-canonical, so you can use that as a reference.

**Comment by FruityLeo** [comment]
I have the same problem.

Thanks for the link, unfortunately I still have no idea how to adjust the configuration. Would you also have a practical example for me or help me out?

I am trying to use the "no-unused-exports" rule. 

I tried the following in my `eslint.config.js`:
``` Javascript
const canonical = require("eslint-plugin-canonical");

module.exports = tseslint.config(
  {
    plugins: {
      canoncial,
    },
    extends: [
      ... // only other rule sets
    ],
    rules: {
      "canonical/no-unused-exports": "error",
    }
  }
);
```

But I get the following error (even when I only add the require statement at the top):
```
An unhandled exception occurred: Cannot find module 'doctrine'
Require stack:
- /Users/project/node_modules/eslint-plugin-canonical/dist/src/rules/ExportMap.js
- /Users/project/node_modules/eslint-plugin-canonical/dist/src/rules/noBarrelImport.js
- /Users/project/node_modules/eslint-plugin-canonical/dist/src/index.js
- /Users/project/eslint.config.js
See ".../angular-errors.log" for further details.
```


Additionally, I wonder if an updated documentation for the flat configuration is useful for other users in the future?

**Comment by rzschoch** [comment]
I'm not sure why it works all of a sudden, but this is how it works for me now. I hope this helps.

```
const eslintPluginCanonical = require("eslint-plugin-canonical");
const typescriptEslint = require("typescript-eslint");

module.exports = typescriptEslint.config(
	{
		files: ["src/**/*.ts"],
		// Only add plugins that are not already included in the extends array
		plugins: {
			canonical: eslintPluginCanonical,
		},
		extends: [
			...typescriptEslint.configs.recommendedTypeChecked,
			...typescriptEslint.configs.stylisticTypeChecked,
		],
		rules: {
			"canonical/no-unused-exports": [
				"error",
				{
					tsConfigPath: "tsconfig.json",
				},
			],
		},
	},
);

```
