### ISSUE TITLE
2.6.0 release to undo 2.5.0

### ISSUE THREAD

**Issue by brettz9** [gajus/eslint-plugin-canonical#4]
@gajus : Although I see you've since moved to a 3.0.0 version, a 2.5.0 version of `eslint-plugin-canonical` was nevertheless released with [breaking changes](https://github.com/gajus/eslint-plugin-canonical/compare/v2.4.3...v2.5.0) (the `node:` specifiers). This causes all projects targeting `^2.0.0`, such as `eslint-plugin-jsdoc` to suddenly start breaking.

Could you put out a 2.6.0 release which reverts those `node:` changes, as the EOL that is coming at the end of this month is only to drop Node 12, not yet to drop Node 14?

Thanks!

**Comment by gajus** [comment]
Yeah, this was indeed a mistake. 2.6.0 released. Thanks Brettz!

**Comment by brettz9** [comment]
hmm--I'm not seeing it at https://www.npmjs.com/package/eslint-plugin-canonical nor when trying via npm. They seem to usually make updates available very quickly these days, so I wonder if something got tripped up during publishing?

**Comment by gajus** [comment]
Sorry about that ... accidentally published eslint-config-canonical v2.6.0

Plugin 2.6.0 published  https://www.npmjs.com/package/eslint-plugin-canonical/v/2.6.0

**Comment by brettz9** [comment]
Great, thanks!
