### ISSUE TITLE
[`prefer-inline-type-import`] Edge Cases Currently Not Handled

### ISSUE THREAD

**Issue by joealden** [gajus/eslint-plugin-canonical#6]
After trying to add this rule to my work codebase, I encountered the following cases where there was no easy way to resolve the lint warnings:

1. Importing a default export and only using its type. There are a few cases where default exports can't be avoided - for example, importing the type of a JSON file (`import type package from "./package.json";`), or a library import than you don't control. In this case, I would personally expect the rule to accept this as valid.
2. Glob type-only imports, for example, `import type * as Types from "./types";`. While this is something that can more easily be worked around compared to the case above (by just explicitly importing the required types), I do still think it is something the rule should handle. As with the above case, I would personally expect the rule to accept this as valid (even if it is via an option).

**Comment by gajus** [comment]
Makes sense! Thanks
