### ISSUE TITLE
Incorporate rules from eslint-plugin-eslint-comments

### ISSUE THREAD

**Issue by nmschulte-aviture** [gajus/eslint-plugin-canonical#9]
In https://github.com/mysticatea/eslint-plugin-eslint-comments/issues/65 you asked about this incorporation, and the author suggests you to do so, and it seems the project won't be receiving much attention: https://github.com/mysticatea/eslint-plugin-eslint-comments/issues/72#issuecomment-1269066073

It would be great to have these rules in ESLint v8.

**Comment by MichaelDeBoey** [comment]
@nmschulte-aviture Where are you seeing the author is suggesting to do so?
I only see questions asked, but no answers from @mysticatea for now

**Comment by nmschulte-aviture** [comment]
Upon review I now realize that "Vages" is not "mysticatea," but I think the point stands.  I bolded the points in the quoted comment below, which given the overarching sentiment I read as the suggestion: https://github.com/mysticatea/eslint-plugin-eslint-comments/issues/65#issuecomment-964891049

> You may already know this, but in case not: This project is MIT licensed, so copying the entire package – or parts of it – is probably **within the boundaries of** the law and **developer courtesy** (as long as you follow the terms of the license): https://github.com/mysticatea/eslint-plugin-eslint-comments/blob/master/LICENSE
> 
> **Looking forward to seeing the rules in eslint-plugin-canonical!**

**Comment by gajus** [comment]
I never got around to doing this, but if someone contributed it, would happily release it.

Legally, it is fine. Just need to include header attributing the original author.

**Comment by MichaelDeBoey** [comment]
@gajus Do you still want to incorporate these rules now that we have the @eslint-community fork
https://github.com/eslint-community/eslint-plugin-eslint-comments

For more info about why we created this organization, you can read https://eslint.org/blog/2023/03/announcing-eslint-community-org

**Comment by gajus** [comment]
Nope. If there is an active maintainer, no need to incorporate them here.
